# Generated by Django 4.0.2 on 2022-02-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название конференции:')),
                ('Country', models.CharField(choices=[('', 'Выберите страну'), ('RU', 'Россия'), ('AB', 'Абхазия'), ('AU', 'Австралия'), ('AT', 'Австрия'), ('AZ', 'Азербайджан'), ('AL', 'Албания'), ('DZ', 'Алжир'), ('AI', 'Ангилья'), ('AO', 'Ангола'), ('AD', 'Андорра'), ('AR', 'Аргентина'), ('AM', 'Армения'), ('AW', 'Аруба'), ('AF', 'Афганистан'), ('BS', 'Багамы'), ('BD', 'Бангладеш'), ('BB', 'Барбадос'), ('BH', 'Бахрейн'), ('BY', 'Беларусь'), ('BZ', 'Белиз'), ('BE', 'Бельгия'), ('BJ', 'Бенин'), ('BM', 'Бермуды'), ('BG', 'Болгария'), ('BO', 'Боливия'), ('BA', 'Босния и Герцеговина'), ('BW', 'Ботсвана'), ('BR', 'Бразилия'), ('BN', 'Бруней-Даруссалам'), ('BF', 'Буркина-Фасо'), ('BI', 'Бурунди'), ('BT', 'Бутан'), ('VU', 'Вануату'), ('GB', 'Великобритания'), ('HU', 'Венгрия'), ('VE', 'Венесуэла'), ('VN', 'Вьетнам'), ('GA', 'Габон'), ('HT', 'Гаити'), ('GY', 'Гайана'), ('GM', 'Гамбия'), ('GH', 'Гана'), ('GP', 'Гваделупа'), ('GT', 'Гватемала'), ('GN', 'Гвинея'), ('GW', 'Гвинея-Бисау'), ('DE', 'Германия'), ('GI', 'Гибралтар'), ('HN', 'Гондурас'), ('HK', 'Гонконг'), ('GD', 'Гренада'), ('GL', 'Гренландия'), ('GR', 'Греция'), ('GE', 'Грузия'), ('GU', 'Гуам'), ('DK', 'Дания'), ('JE', 'Джерси'), ('DJ', 'Джибути'), ('DM', 'Доминика'), ('DO', 'ДоминиканскаяРеспублика'), ('EG', 'Египет'), ('ZM', 'Замбия'), ('ZW', 'Зимбабве'), ('IL', 'Израиль'), ('IN', 'Индия'), ('ID', 'Индонезия'), ('JO', 'Иордания'), ('IQ', 'Ирак'), ('IR', 'Иран'), ('IE', 'Ирландия'), ('IS', 'Исландия'), ('ES', 'Испания'), ('IT', 'Италия'), ('YE', 'Йемен'), ('CV', 'Кабо-Верде'), ('KZ', 'Казахстан'), ('KH', 'Камбоджа'), ('CM', 'Камерун'), ('CA', 'Канада'), ('QA', 'Катар'), ('KE', 'Кения'), ('CY', 'Кипр'), ('KG', 'Киргизия'), ('CN', 'Китай'), ('CO', 'Колумбия'), ('KM', 'Коморы'), ('CG', 'Конго'), ('CD', 'Конго'), ('KP', 'КНДР'), ('KR', 'Республика Корея'), ('CR', 'Коста-Рика'), ('CU', 'Куба'), ('KW', 'Кувейт'), ('CW', 'Кюрасао'), ('LA', 'Лаос'), ('LV', 'Латвия'), ('LS', 'Лесото'), ('LB', 'Ливан'), ('LY', 'Ливийская Арабская Джамахирия'), ('LR', 'Либерия'), ('LI', 'Лихтенштейн'), ('LT', 'Литва'), ('LU', 'Люксембург'), ('MU', 'Маврикий'), ('MR', 'Мавритания'), ('MG', 'Мадагаскар'), ('YT', 'Майотта'), ('MO', 'Макао'), ('MW', 'Малави'), ('MY', 'Малайзия'), ('ML', 'Мали'), ('MV', 'Мальдивы'), ('MT', 'Мальта'), ('MA', 'Марокко'), ('MQ', 'Мартиника'), ('MX', 'Мексика'), ('MZ', 'Мозамбик'), ('MD', 'Молдова'), ('MC', 'Монако'), ('MN', 'Монголия'), ('MS', 'Монтсеррат'), ('MM', 'Мьянма'), ('NA', 'Намибия'), ('NR', 'Науру'), ('NP', 'Непал'), ('NE', 'Нигер'), ('NG', 'Нигерия'), ('NL', 'Нидерланды'), ('NI', 'Никарагуа'), ('NZ', 'Новая Зеландия'), ('NC', 'Новая Каледония'), ('NO', 'Норвегия'), ('AE', 'ОАЭ'), ('OM', 'Оман'), ('PK', 'Пакистан'), ('PA', 'Панама'), ('PG', 'Папуа-Новая Гвинея'), ('PY', 'Парагвай'), ('PE', 'Перу'), ('PL', 'Польша'), ('PT', 'Португалия'), ('PR', 'Пуэрто-Рико'), ('MK', 'Республика Македония'), ('RW', 'Руанда'), ('RO', 'Румыния'), ('WS', 'Самоа'), ('SM', 'Сан-Марино'), ('SA', 'СаудовскаяАравия'), ('SN', 'Сенегал'), ('RS', 'Сербия'), ('SC', 'Сейшелы'), ('SG', 'Сингапур'), ('SY', 'Сирийская Арабская Республика'), ('SK', 'Словакия'), ('SI', 'Словения'), ('US', 'Соединенные Штаты'), ('SO', 'Сомали'), ('SD', 'Судан'), ('SR', 'Суринам'), ('SL', 'Сьерра-Леоне'), ('TJ', 'Таджикистан'), ('TH', 'Таиланд'), ('TW', 'Тайвань (Китай)'), ('TZ', 'Танзания'), ('TL', 'Тимор-Лесте'), ('TG', 'Того'), ('TK', 'Токелау'), ('TO', 'Тонга'), ('TT', 'Тринидади Тобаго'), ('TV', 'Тувалу'), ('TN', 'Тунис'), ('TM', 'Туркмения'), ('TR', 'Турция'), ('UG', 'Уганда'), ('UZ', 'Узбекистан'), ('UA', 'Украина'), ('UY', 'Уругвай'), ('FO', 'Фарерские острова'), ('FJ', 'Фиджи'), ('PH', 'Филиппины'), ('FI', 'Финляндия'), ('FR', 'Франция'), ('HR', 'Хорватия'), ('CF', 'Центрально-Африканская Республика'), ('TD', 'Чад'), ('ME', 'Черногория'), ('CZ', 'Чехия'), ('CL', 'Чили'), ('CH', 'Швейцария'), ('SE', 'Швеция'), ('LK', 'Шри-Ланка'), ('EC', 'Эквадор'), ('GQ', 'Экваториальная Гвинея'), ('EE', 'Эстония'), ('ET', 'Эфиопия'), ('ZA', 'Южная Африка'), ('OS', 'Южная Осетия'), ('SS', 'Южный Судан'), ('JM', 'Ямайка'), ('JP', 'Япония')], max_length=2, verbose_name='Страна проведения:')),
                ('City', models.CharField(max_length=30, verbose_name='Город проведения:')),
                ('Status', models.CharField(choices=[('', 'Выберите статус'), ('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка.', max_length=2, verbose_name='Статус:')),
                ('Month', models.CharField(choices=[('', 'Выберите месяц'), ('Ja', 'Январь'), ('Fe', 'Февраль'), ('Mar', 'Март'), ('Ap', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Au', 'Август'), ('Se', 'Сентябрь'), ('Oc', 'Октябрь'), ('No', 'Ноябрь'), ('De', 'Декабрь')], default='', max_length=3, verbose_name='Месяц проведения:')),
                ('Organizer', models.BooleanField(default=False, help_text='Поставьте галочку, если ГУУ является организатором конференции.', verbose_name='Организатор ГУУ')),
                ('Student', models.BooleanField(default=False, help_text='Поставьте галочку, если конференция является студенческой.', verbose_name='Студенческая')),
                ('Total', models.IntegerField(help_text='Введите примерное количество участников.', verbose_name='Общее число участников:')),
                ('Delegate', models.IntegerField(help_text='Введите количество представителей ГУУ, участвующих в конференции.', verbose_name='В том числе от ГУУ:')),
                ('Url', models.URLField(blank=True, help_text='Ссылка должна начинаться с http:// или https:// (например: https://yandex.ru/)', verbose_name='Ссылка на конференцию')),
                ('Email', models.EmailField(blank=True, help_text='Укажите свой email. По данному email можно видеть все внесенные Вами конференции.', max_length=254, null=True, verbose_name='Email:')),
                ('Comment', models.TextField(blank=True, null=True, verbose_name='Комментарий:')),
                ('TimeCreate', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Конференцию',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедру',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Введите имя.', max_length=20, verbose_name='Имя')),
                ('MiddleName', models.CharField(blank=True, help_text='Введите отчество (при наличии).', max_length=20, verbose_name='Отчество')),
                ('Surname', models.CharField(help_text='Введите фамилию.', max_length=30, verbose_name='Фамилия')),
                ('PrevSurname', models.CharField(blank=True, default='No', help_text='Если меняли фамилию, то введите предыдущую.', max_length=30, verbose_name='Предыдущая Фамилия')),
                ('Position', models.CharField(choices=[('', 'Выберите должность'), ('МНС', 'младший научный сотрудник'), ('НС', 'научный сотрудник'), ('СНС', 'старший научный сотрудник'), ('ВНС', 'ведущий научный сотрудник'), ('ГНС', 'главный научный сотрудник'), ('АП', 'ассистент преподавателя'), ('ПР', 'преподаватель'), ('СПР', 'старший преподаватель'), ('ДОЦ', 'доцент'), ('ПРОФ', 'профессор'), ('НР', 'научный работник'), ('ИТР', 'инженерно-технический работник'), ('ДР', 'другое')], help_text='Выберите должность.', max_length=20, verbose_name='Должность')),
                ('Degree', models.CharField(blank=True, choices=[('', 'Выберите степень'), ('ДОКТ', 'доктор'), ('КАНД', 'кандидат'), ('БС', 'без степени')], default='No', help_text='Выберете ученую степень.', max_length=20, verbose_name='Ученая степень')),
                ('TypeWork', models.CharField(choices=[('', 'Выберите тип'), ('О', 'основной'), ('В', 'внешний')], help_text='Выберете тип трудовых отношений.', max_length=20, verbose_name='Тип трудовых отношений')),
                ('Year', models.CharField(blank=True, default='1900', help_text='Введите год рождения', max_length=4, verbose_name='Год рождения')),
                ('Identifier', models.CharField(blank=True, default='0000', help_text='Введите 4 последние цифры СНИЛС.', max_length=4, verbose_name='СНИЛС')),
                ('Email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('Departure', models.ForeignKey(blank=True, help_text='Выберите название кафедры.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departure', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподавателя',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'required': 'Please enter your name'}, max_length=70, verbose_name='Название')),
                ('ShortName', models.CharField(max_length=10, verbose_name='Аббревиатура')),
                ('IdDeputeScience', models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Depute', to='main.employee', verbose_name='Зам.директора по науке')),
                ('IdDirector', models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Director', to='main.employee', verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='IdInstitute',
            field=models.ForeignKey(help_text='Выберите название института.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institute', verbose_name='Институт'),
        ),
    ]
