# Generated by Django 4.0.1 on 2022-01-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедру',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Введите имя', max_length=20, verbose_name='Имя')),
                ('MiddleName', models.CharField(blank=True, help_text='Введите отчество (при наличии)', max_length=20, verbose_name='Отчество')),
                ('Surname', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='Фамилия')),
                ('PrevSurname', models.CharField(blank=True, help_text='Если меняли фамилию, то введите предыдущую', max_length=30, verbose_name='Предыдущая Фамилия')),
                ('Position', models.CharField(choices=[('МНС', 'младший научный сотрудник'), ('НС', 'научный сотрудник'), ('СНС', 'старший научный сотрудник'), ('ВНС', 'ведущий научный сотрудник'), ('ГНС', 'главный научный сотрудник'), ('АП', 'ассистент преподавателя'), ('ПР', 'преподаватель'), ('СПР', 'старший преподаватель'), ('ДОЦ', 'доцент'), ('ПРОФ', 'профессор'), ('НР', 'научный работник'), ('ИТР', 'инженерно-технический работник'), ('ДР', 'другое')], help_text='Выберите должность', max_length=20, verbose_name='Должность')),
                ('Degree', models.CharField(choices=[('ДОКТ', 'доктор'), ('КАНД', 'кандидат'), ('БС', 'без степени')], help_text='Выберете ученую степень', max_length=20, verbose_name='Ученая степень')),
                ('TypeWork', models.CharField(choices=[('О', 'основной'), ('В', 'внешний')], help_text='Выберете тип трудовых отношений', max_length=20, verbose_name='Тип трудовых отношений')),
                ('Year', models.CharField(help_text='Введите год рождения', max_length=4, verbose_name='Год рождения')),
                ('Identifier', models.CharField(help_text='Введите 4 последние цифры СНИЛС', max_length=4, verbose_name='СНИЛС')),
                ('Email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('Departure', models.ForeignKey(default=None, help_text='Выберите название кафедры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departure')),
            ],
            options={
                'verbose_name': 'Преподавателя',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, verbose_name='Название')),
                ('ShortName', models.CharField(max_length=10, verbose_name='Аббревиатура')),
                ('IdDeputeScience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Depute', to='main.employee')),
                ('IdDirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Director', to='main.employee')),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='IdInstitute',
            field=models.ForeignKey(help_text='Выберите название института', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institute'),
        ),
    ]
