# Generated by Django 4.0.1 on 2022-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('Answer', models.TextField(verbose_name='Ответ')),
                ('Link', models.URLField(blank=True, help_text='Ссылка должна начинаться с http:// или https:// (например: https://yandex.ru/)', null=True, verbose_name='Ссылка на видео (при наличии)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='conference',
            name='Status',
            field=models.CharField(choices=[('', 'Выберите статус'), ('М', 'Международная'), ('Р', 'Российская'), ('Ре', 'Региональная')], help_text='Выберите из списка.', max_length=2, verbose_name='Статус:'),
        ),
    ]
