# Generated by Django 4.0.1 on 2022-01-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='IdInstitute',
            field=models.ForeignKey(help_text='Выберите название института', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institute', verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Degree',
            field=models.CharField(blank=True, choices=[('ДОКТ', 'доктор'), ('КАНД', 'кандидат'), ('БС', 'без степени')], default='No', help_text='Выберете ученую степень', max_length=20, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Identifier',
            field=models.CharField(blank=True, default='0000', help_text='Введите 4 последние цифры СНИЛС', max_length=4, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PrevSurname',
            field=models.CharField(blank=True, default='No', help_text='Если меняли фамилию, то введите предыдущую', max_length=30, verbose_name='Предыдущая Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Year',
            field=models.CharField(blank=True, default='1900', help_text='Введите год рождения', max_length=4, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='IdDeputeScience',
            field=models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Depute', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='IdDirector',
            field=models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Director', to='main.employee'),
        ),
    ]
