# Generated by Django 4.0.1 on 2022-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_departure_idinstitute_alter_employee_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название конференции')),
                ('Country', models.CharField(max_length=60, verbose_name='Страна проведения')),
                ('City', models.CharField(max_length=30, verbose_name='Город проведения')),
                ('Status', models.CharField(choices=[('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка', max_length=1, verbose_name='Статус')),
                ('Total', models.IntegerField(help_text='Введите примерное количество участников', verbose_name='Общее число участников (Оценка)')),
                ('Delegate', models.IntegerField(help_text='Введите количество представителей ГУУ, участвующих в конференции', verbose_name='Количество представителей от ГУУ')),
                ('Url', models.URLField(help_text='Укажите ссылку в РИНЦ (предпочтительно) или на сайт конференции.', verbose_name='Ссылка на конференцию')),
                ('Email', models.EmailField(blank=True, help_text='Укажите свой email. В дальнейшем будет реализована возможность по email видетьвсе внесенные ранее конференции', max_length=254, null=True, verbose_name='Email')),
                ('Comment', models.TextField(blank='True', verbose_name='Комментарий')),
            ],
        ),
    ]
