# Generated by Django 4.0.2 on 2022-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vak_options_remove_vak_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='DepartmentOther',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы с других кафедр ГУУ'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='DepartmentSame',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы ГУУ с отчетной кафедры'),
        ),
        migrations.AlterField(
            model_name='thesisnation',
            name='DepartmentOther',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы с других кафедр ГУУ'),
        ),
        migrations.AlterField(
            model_name='thesisnation',
            name='DepartmentSame',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы ГУУ с отчетной кафедры'),
        ),
        migrations.AlterField(
            model_name='thesisworld',
            name='DepartmentOther',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы с других кафедр ГУУ'),
        ),
        migrations.AlterField(
            model_name='thesisworld',
            name='DepartmentSame',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы ГУУ с отчетной кафедры'),
        ),
        migrations.AlterField(
            model_name='vak',
            name='DepartmentOther',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы с других кафедр ГУУ'),
        ),
        migrations.AlterField(
            model_name='vak',
            name='DepartmentSame',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторы ГУУ с отчетной кафедры'),
        ),
    ]
