# Generated by Django 4.0.1 on 2022-01-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_conference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Конференцию', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AlterField(
            model_name='conference',
            name='Country',
            field=models.CharField(help_text='Если Россия, то укажите "РФ".', max_length=60, verbose_name='Страна проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Delegate',
            field=models.IntegerField(help_text='Введите количество представителей ГУУ, участвующих в конференции.', verbose_name='В том числе от ГУУ'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Email',
            field=models.EmailField(blank=True, help_text='Укажите свой email. В дальнейшем будет реализована возможность по email видетьвсе внесенные ранее конференции.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Status',
            field=models.CharField(choices=[('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка.', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Total',
            field=models.IntegerField(help_text='Введите примерное количество участников.', verbose_name='Общее число участников'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Url',
            field=models.URLField(blank=True, default='https://', help_text='Укажите ссылку в РИНЦ (предпочтительно) или на сайт конференции.', verbose_name='Ссылка на конференцию'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='IdInstitute',
            field=models.ForeignKey(help_text='Выберите название института.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institute', verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Degree',
            field=models.CharField(blank=True, choices=[('ДОКТ', 'доктор'), ('КАНД', 'кандидат'), ('БС', 'без степени')], default='No', help_text='Выберете ученую степень.', max_length=20, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Departure',
            field=models.ForeignKey(blank=True, help_text='Выберите название кафедры.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departure', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Identifier',
            field=models.CharField(blank=True, default='0000', help_text='Введите 4 последние цифры СНИЛС.', max_length=4, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MiddleName',
            field=models.CharField(blank=True, help_text='Введите отчество (при наличии).', max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Name',
            field=models.CharField(help_text='Введите имя.', max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Position',
            field=models.CharField(choices=[('МНС', 'младший научный сотрудник'), ('НС', 'научный сотрудник'), ('СНС', 'старший научный сотрудник'), ('ВНС', 'ведущий научный сотрудник'), ('ГНС', 'главный научный сотрудник'), ('АП', 'ассистент преподавателя'), ('ПР', 'преподаватель'), ('СПР', 'старший преподаватель'), ('ДОЦ', 'доцент'), ('ПРОФ', 'профессор'), ('НР', 'научный работник'), ('ИТР', 'инженерно-технический работник'), ('ДР', 'другое')], help_text='Выберите должность.', max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PrevSurname',
            field=models.CharField(blank=True, default='No', help_text='Если меняли фамилию, то введите предыдущую.', max_length=30, verbose_name='Предыдущая Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Surname',
            field=models.CharField(help_text='Введите фамилию.', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TypeWork',
            field=models.CharField(choices=[('О', 'основной'), ('В', 'внешний')], help_text='Выберете тип трудовых отношений.', max_length=20, verbose_name='Тип трудовых отношений'),
        ),
    ]
