# Generated by Django 4.0.1 on 2022-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_conference_options_alter_conference_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='City',
            field=models.CharField(max_length=30, verbose_name='Город проведения:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Country',
            field=models.CharField(choices=[('RU', 'Россия'), ('US', '')], help_text='Если Россия, то укажите "РФ".', max_length=60, verbose_name='Страна проведения:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Название конференции:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Status',
            field=models.CharField(choices=[('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка.', max_length=3, verbose_name='Статус:'),
        ),
    ]
