# Generated by Django 4.0.1 on 2022-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_conference_city_alter_conference_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Country',
            field=models.CharField(choices=[('RU', 'Россия'), ('US', 'США')], max_length=2, verbose_name='Страна проведения:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Status',
            field=models.CharField(choices=[('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка.', max_length=2, verbose_name='Статус:'),
        ),
    ]
