# Generated by Django 4.0.1 on 2022-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_thesis_remove_thesisworld_iddeparture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='PlanMonograph',
            field=models.IntegerField(default=0, verbose_name='Монографии. План'),
        ),
        migrations.AddField(
            model_name='departure',
            name='PlanVak',
            field=models.IntegerField(default=0, verbose_name='Публикации ВАК. План'),
        ),
        migrations.AddField(
            model_name='departure',
            name='PlanthesisNation',
            field=models.IntegerField(default=0, verbose_name='Тезисы в Нац. конференциях. План'),
        ),
        migrations.AddField(
            model_name='departure',
            name='PlanthesisWorld',
            field=models.IntegerField(default=0, verbose_name='Тезисы в Межд. конференциях. План'),
        ),
    ]
