# Generated by Django 4.0.2 on 2022-08-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_departure_planmonograph_departure_planvak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='Points',
            field=models.FloatField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='Points',
            field=models.FloatField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='vak',
            name='Points',
            field=models.FloatField(default=0, verbose_name='Количество баллов'),
        ),
    ]
