# Generated by Django 4.0.1 on 2022-02-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_conference_country_alter_conference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Organizer',
            field=models.CharField(blank=True, choices=[('', 'Выберите да/нет'), ('Y', 'Да'), ('N', 'Нет')], help_text='Выберите из списка,', max_length=2, null=True, verbose_name='Огранизатор конференции ГУУ:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Country',
            field=models.CharField(choices=[('', 'Выберите страну'), ('RU', 'Россия'), ('AB', 'Абхазия'), ('AU', 'Австралия'), ('AT', 'Австрия'), ('AZ', 'Азербайджан'), ('AL', 'Албания'), ('DZ', 'Алжир'), ('AI', 'Ангилья'), ('AO', 'Ангола'), ('AD', 'Андорра'), ('AR', 'Аргентина'), ('AM', 'Армения'), ('AW', 'Аруба'), ('AF', 'Афганистан'), ('BS', 'Багамы'), ('BD', 'Бангладеш'), ('BB', 'Барбадос'), ('BH', 'Бахрейн'), ('BY', 'Беларусь'), ('BZ', 'Белиз'), ('BE', 'Бельгия'), ('BJ', 'Бенин'), ('BM', 'Бермуды'), ('BG', 'Болгария'), ('BO', 'Боливия'), ('BA', 'Босния и Герцеговина'), ('BW', 'Ботсвана'), ('BR', 'Бразилия'), ('BN', 'Бруней-Даруссалам'), ('BF', 'Буркина-Фасо'), ('BI', 'Бурунди'), ('BT', 'Бутан'), ('VU', 'Вануату'), ('GB', 'Великобритания'), ('HU', 'Венгрия'), ('VE', 'Венесуэла'), ('VN', 'Вьетнам'), ('GA', 'Габон'), ('HT', 'Гаити'), ('GY', 'Гайана'), ('GM', 'Гамбия'), ('GH', 'Гана'), ('GP', 'Гваделупа'), ('GT', 'Гватемала'), ('GN', 'Гвинея'), ('GW', 'Гвинея-Бисау'), ('DE', 'Германия'), ('GI', 'Гибралтар'), ('HN', 'Гондурас'), ('HK', 'Гонконг'), ('GD', 'Гренада'), ('GL', 'Гренландия'), ('GR', 'Греция'), ('GE', 'Грузия'), ('GU', 'Гуам'), ('DK', 'Дания'), ('JE', 'Джерси'), ('DJ', 'Джибути'), ('DM', 'Доминика'), ('DO', 'ДоминиканскаяРеспублика'), ('EG', 'Египет'), ('ZM', 'Замбия'), ('ZW', 'Зимбабве'), ('IL', 'Израиль'), ('IN', 'Индия'), ('ID', 'Индонезия'), ('JO', 'Иордания'), ('IQ', 'Ирак'), ('IR', 'Иран'), ('IE', 'Ирландия'), ('IS', 'Исландия'), ('ES', 'Испания'), ('IT', 'Италия'), ('YE', 'Йемен'), ('CV', 'Кабо-Верде'), ('KZ', 'Казахстан'), ('KH', 'Камбоджа'), ('CM', 'Камерун'), ('CA', 'Канада'), ('QA', 'Катар'), ('KE', 'Кения'), ('CY', 'Кипр'), ('KG', 'Киргизия'), ('CN', 'Китай'), ('CO', 'Колумбия'), ('KM', 'Коморы'), ('CG', 'Конго'), ('CD', 'Конго'), ('KP', 'КНДР'), ('KR', 'Республика Корея'), ('CR', 'Коста-Рика'), ('CU', 'Куба'), ('KW', 'Кувейт'), ('CW', 'Кюрасао'), ('LA', 'Лаос'), ('LV', 'Латвия'), ('LS', 'Лесото'), ('LB', 'Ливан'), ('LY', 'Ливийская Арабская Джамахирия'), ('LR', 'Либерия'), ('LI', 'Лихтенштейн'), ('LT', 'Литва'), ('LU', 'Люксембург'), ('MU', 'Маврикий'), ('MR', 'Мавритания'), ('MG', 'Мадагаскар'), ('YT', 'Майотта'), ('MO', 'Макао'), ('MW', 'Малави'), ('MY', 'Малайзия'), ('ML', 'Мали'), ('MV', 'Мальдивы'), ('MT', 'Мальта'), ('MA', 'Марокко'), ('MQ', 'Мартиника'), ('MX', 'Мексика'), ('MZ', 'Мозамбик'), ('MD', 'Молдова'), ('MC', 'Монако'), ('MN', 'Монголия'), ('MS', 'Монтсеррат'), ('MM', 'Мьянма'), ('NA', 'Намибия'), ('NR', 'Науру'), ('NP', 'Непал'), ('NE', 'Нигер'), ('NG', 'Нигерия'), ('NL', 'Нидерланды'), ('NI', 'Никарагуа'), ('NZ', 'Новая Зеландия'), ('NC', 'Новая Каледония'), ('NO', 'Норвегия'), ('AE', 'ОАЭ'), ('OM', 'Оман'), ('PK', 'Пакистан'), ('PA', 'Панама'), ('PG', 'Папуа-Новая Гвинея'), ('PY', 'Парагвай'), ('PE', 'Перу'), ('PL', 'Польша'), ('PT', 'Португалия'), ('PR', 'Пуэрто-Рико'), ('MK', 'Республика Македония'), ('RW', 'Руанда'), ('RO', 'Румыния'), ('WS', 'Самоа'), ('SM', 'Сан-Марино'), ('SA', 'СаудовскаяАравия'), ('SN', 'Сенегал'), ('RS', 'Сербия'), ('SC', 'Сейшелы'), ('SG', 'Сингапур'), ('SY', 'Сирийская Арабская Республика'), ('SK', 'Словакия'), ('SI', 'Словения'), ('US', 'Соединенные Штаты'), ('SO', 'Сомали'), ('SD', 'Судан'), ('SR', 'Суринам'), ('SL', 'Сьерра-Леоне'), ('TJ', 'Таджикистан'), ('TH', 'Таиланд'), ('TW', 'Тайвань (Китай)'), ('TZ', 'Танзания'), ('TL', 'Тимор-Лесте'), ('TG', 'Того'), ('TK', 'Токелау'), ('TO', 'Тонга'), ('TT', 'Тринидади Тобаго'), ('TV', 'Тувалу'), ('TN', 'Тунис'), ('TM', 'Туркмения'), ('TR', 'Турция'), ('UG', 'Уганда'), ('UZ', 'Узбекистан'), ('UA', 'Украина'), ('UY', 'Уругвай'), ('FO', 'Фарерские острова'), ('FJ', 'Фиджи'), ('PH', 'Филиппины'), ('FI', 'Финляндия'), ('FR', 'Франция'), ('HR', 'Хорватия'), ('CF', 'Центрально-Африканская Республика'), ('TD', 'Чад'), ('ME', 'Черногория'), ('CZ', 'Чехия'), ('CL', 'Чили'), ('CH', 'Швейцария'), ('SE', 'Швеция'), ('LK', 'Шри-Ланка'), ('EC', 'Эквадор'), ('GQ', 'Экваториальная Гвинея'), ('EE', 'Эстония'), ('ET', 'Эфиопия'), ('ZA', 'Южная Африка'), ('OS', 'Южная Осетия'), ('SS', 'Южный Судан'), ('JM', 'Ямайка'), ('JP', 'Япония')], max_length=2, verbose_name='Страна проведения:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Delegate',
            field=models.IntegerField(help_text='Введите количество представителей ГУУ, участвующих в конференции.', verbose_name='В том числе от ГУУ:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Email',
            field=models.EmailField(blank=True, help_text='Укажите свой email. В дальнейшем будет реализована возможность по email видетьвсе внесенные ранее конференции.', max_length=254, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Status',
            field=models.CharField(choices=[('', 'Выберите статус'), ('М', 'Международная'), ('Р', 'Российская'), ('В', 'Внутренняя')], help_text='Выберите из списка.', max_length=2, verbose_name='Статус:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Total',
            field=models.IntegerField(help_text='Введите примерное количество участников.', verbose_name='Общее число участников:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Url',
            field=models.URLField(blank=True, help_text='Укажите ссылку в РИНЦ (предпочтительно) или на сайт конференции.', verbose_name='Ссылка на конференцию'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Degree',
            field=models.CharField(blank=True, choices=[('', 'Выберите степень'), ('ДОКТ', 'доктор'), ('КАНД', 'кандидат'), ('БС', 'без степени')], default='No', help_text='Выберете ученую степень.', max_length=20, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Position',
            field=models.CharField(choices=[('', 'Выберите должность'), ('МНС', 'младший научный сотрудник'), ('НС', 'научный сотрудник'), ('СНС', 'старший научный сотрудник'), ('ВНС', 'ведущий научный сотрудник'), ('ГНС', 'главный научный сотрудник'), ('АП', 'ассистент преподавателя'), ('ПР', 'преподаватель'), ('СПР', 'старший преподаватель'), ('ДОЦ', 'доцент'), ('ПРОФ', 'профессор'), ('НР', 'научный работник'), ('ИТР', 'инженерно-технический работник'), ('ДР', 'другое')], help_text='Выберите должность.', max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TypeWork',
            field=models.CharField(choices=[('', 'Выберите тип'), ('О', 'основной'), ('В', 'внешний')], help_text='Выберете тип трудовых отношений.', max_length=20, verbose_name='Тип трудовых отношений'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='IdDeputeScience',
            field=models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Depute', to='main.employee', verbose_name='Зам.директора по науке'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='IdDirector',
            field=models.ForeignKey(blank=True, default='No', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Director', to='main.employee', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='Name',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=70, verbose_name='Название'),
        ),
    ]
