# Generated by Django 4.0.1 on 2022-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_conference_organizer_alter_conference_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Month',
            field=models.CharField(choices=[('', 'Выберите месяц'), ('Ja', 'Январь'), ('Fe', 'Февраль'), ('Mar', 'Март'), ('Ap', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Au', 'Август'), ('Se', 'Сентябрь'), ('Oc', 'Октябрь'), ('No', 'Ноябрь'), ('De', 'Декабрь')], default='', max_length=3, verbose_name='Страна проведения:'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Organizer',
            field=models.CharField(blank=True, choices=[('', 'Выберите да/нет'), ('Y', 'Да'), ('N', 'Нет')], help_text='Выберите из списка,', max_length=2, null=True, verbose_name='Организатор ГУУ:'),
        ),
    ]
