# Generated by Django 4.0.2 on 2022-08-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_monograph_points_alter_thesis_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monograph',
            name='Admitted',
            field=models.ManyToManyField(blank=True, to='main.Employee', verbose_name='Редакторы'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='Admitted',
            field=models.ManyToManyField(blank=True, to='main.Employee', verbose_name='Редакторы'),
        ),
        migrations.AddField(
            model_name='vak',
            name='Admitted',
            field=models.ManyToManyField(blank=True, to='main.Employee', verbose_name='Редакторы'),
        ),
    ]
