# Generated by Django 4.0.1 on 2022-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_conference_month_alter_conference_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Month',
            field=models.CharField(choices=[('', 'Выберите месяц'), ('Ja', 'Январь'), ('Fe', 'Февраль'), ('Mar', 'Март'), ('Ap', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Au', 'Август'), ('Se', 'Сентябрь'), ('Oc', 'Октябрь'), ('No', 'Ноябрь'), ('De', 'Декабрь')], default='', max_length=3, verbose_name='Месяц проведения:'),
        ),
    ]
