# Generated by Django 4.0.2 on 2022-11-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_monograph_admitted_remove_thesis_admitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='FactIncome',
            field=models.IntegerField(default=0, verbose_name='Фактический объем дохода'),
        ),
        migrations.AddField(
            model_name='departure',
            name='FactRID',
            field=models.IntegerField(default=0, verbose_name='РИД. Факт'),
        ),
        migrations.AddField(
            model_name='departure',
            name='PlanIncome',
            field=models.IntegerField(default=0, verbose_name='Плановый объем дохода'),
        ),
        migrations.AddField(
            model_name='departure',
            name='PlanRID',
            field=models.IntegerField(default=0, verbose_name='РИД. План'),
        ),
    ]
