# Generated by Django 4.0.2 on 2022-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_departure_factincome_departure_factrid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monograph',
            options={'verbose_name': 'Монография', 'verbose_name_plural': 'Монографии'},
        ),
        migrations.AlterField(
            model_name='departure',
            name='FactIncome',
            field=models.IntegerField(default=0, verbose_name='Фактический объем дохода, тыс.руб.'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='PlanIncome',
            field=models.IntegerField(default=0, verbose_name='Плановый объем дохода, тыс.руб.'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='Name',
            field=models.CharField(max_length=250, verbose_name='Название монографии'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='Output',
            field=models.CharField(max_length=100, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='Points',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество баллов: '),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='Points',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество баллов: '),
        ),
        migrations.AlterField(
            model_name='vak',
            name='Points',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество баллов: '),
        ),
    ]
