# Generated by Django 4.0.1 on 2022-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_conference_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Student',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, если конференция является студенческой.', verbose_name='Студенческая'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Organizer',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, если ГУУ является организатором конференции.', verbose_name='Организатор ГУУ'),
        ),
    ]
