# Generated by Django 4.0.1 on 2022-02-12 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_conference_student_alter_conference_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='TimeCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
