from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vakList', views.VakListView.as_view(), name='vakList'),
    path('thesisList', views.ThesisListView.as_view(), name='thesisList'),
    path('monographList', views.MonographListView.as_view(), name='monographList'),
    path('bd/', views.vvod, name="vvod"),
    path('institute', views.institute, name='institute'),
    path('department', views.department, name='department'),
    path('lecturer', views.lecturer, name='lecturer'),
    path('conference', views.conference, name='conference'),
    path('history', views.history, name='history'),
    path('faq', views.faq, name='faq'),
    path('success', views.success, name='success'),
    path('export', views.export, name='export'),
    path('export_pf_all/<int:year>', views.export_pf_all, name='export_pf_all'),
    path('export_pf/<int:institute_id>/<int:year>', views.export_pf, name='export_pf'),
    path('export_publications/<str:model>', views.export_publications_csv, name='export_publications'),
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('change-password/', views.PassChangeView.as_view(), name='change-password'),
    path('change-password/done/', views.PassChangeDoneView.as_view(), name='password_change_done'),
    path('profile', views.profile, name='profile'),
    path('vak', views.vak, name='vak'),
    path('edit/<int:feature_id>/<str:feature>', views.edit, name='edit'),
    path('main/<int:year>', views.main, name='main'),
    path('thesis', views.thesis, name='thesis'),
    path('monograph', views.monograph, name='monograph'),
    path('income', views.income, name='income'),
    path('rid', views.rid, name='rid'),
    path('report/<int:institute_id>/<int:year>', views.report, name='report'),
    path('catalogue/<int:department_id>/<str:feature>/<int:year>', views.catalogue, name='catalogue'),
]
